# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', max_length=200)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('isCompleted', models.BooleanField(default='false')),
            ],
        ),
    ]
